# Generated by Django 4.2.16 on 2025-11-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
    ]
